'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const places=require('../scripts/naver_places'),tmap=require('../scripts/tmap'),planner=require('../scripts/planner'),trip=require('../scripts/trip'),roads=require('../scripts/roads'),f=require('./cargo_fixtures');
const checks=[],copy=x=>JSON.parse(JSON.stringify(x));
function test(name,fn){try{fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.stack});}}
function capture(){return {version:1,kind:'place',selectionKey:'place:101',placeID:'101',name:'가상 거래처',address:'대전 중구 유천로 35',roadAddress:'대전 중구 유천로 35',jibunAddress:'',sourceURL:'https://map.naver.com/p/entry/place/101',coordinate:null,point:null,tileZoom:null,screenResolutionMeters:null,coordinateIssue:'지도 가림',capturedAt:'2026-10-09T00:00:00.000Z',method:'rendered_selected_place_detail'};}
const candidates=()=>[{address:'대전광역시 중구 유천로 35',countryCode:'KR',coordinate:{longitude:127.398,latitude:36.316}}];
function plan(){const p=f.plan([f.visit('A'),f.visit('B')],{enabled:false});p.tmapOrigin={longitude:127.39,latitude:36.31};p.visits.forEach((v,i)=>v.tmapCoordinate={longitude:127.4+i*.01,latitude:36.32});return p;}
function master(){return [{id:'origin',name:'새 출발지',template:{...f.visit('origin-template'),tmapCoordinate:{longitude:127.5,latitude:36.4}},capture:null},{id:'finish',name:'새 도착지',template:{...f.visit('finish-template'),tmapCoordinate:{longitude:127.6,latitude:36.5}},capture:null}];}
function endpoints(p,more={}){return places.endpoints({plan:p,customers:master(),originID:'origin',endMode:'custom',destinationID:'finish',...more});}
test('주소를 건물 좌표와 네이버 경로 지점으로 변환하고 원래 선택 ID 보존',()=>{const c=capture(),r=places.geocode({capture:c,candidates:candidates()});assert.deepEqual(r.coordinate,candidates()[0].coordinate);assert.equal(r.geocodeProvider,'Apple');assert.equal(r.selectionKey,c.selectionKey);assert.equal(r.address,c.address);assert.equal(r.screenResolutionMeters,null);assert.equal(r.tileZoom,null);assert(places.validate(r));assert.equal(c.coordinate,null);});
test('다른 건물번호·도시·도로·국가·지역 중심 좌표는 거부',()=>{for(const change of [{address:'대전 중구 유천로 36'},{address:'서울 중구 유천로 35'},{address:'대전 중구 유천길 35'},{address:'대전 중구 유천로'},{countryCode:'US'},{coordinate:{longitude:0,latitude:0}}])assert.throws(()=>places.geocode({capture:capture(),candidates:[{...candidates()[0],...change}]}));});
test('같은 도로주소에 여러 후보 좌표가 떨어져 있으면 거부',()=>{assert.throws(()=>places.geocode({capture:capture(),candidates:[...candidates(),{...candidates()[0],coordinate:{longitude:127.399,latitude:36.316}}]}),/여러 좌표/);});
test('광역시·도 표기와 도로번호는 정규화하되 35와 350을 혼동하지 않음',()=>{assert(places.addressMatches('대전 중구 유천로 35','대한민국 대전광역시 중구 유천로 35'));assert(!places.addressMatches('대전 중구 유천로 35','대전광역시 중구 유천로 350'));assert(places.addressMatches('경기 성남시 분당구 대왕판교로 606','경기도 성남시 분당구 대왕판교로 606'));assert(places.addressMatches('대전 중구 유천로35번길 6','대전광역시 중구 유천로35번길 6'));});
test('지번주소는 전체 주소 일치가 필요하며 동 중심점은 허용하지 않음',()=>{assert(places.addressMatches('대전 중구 유천동 100-1','대전광역시 중구 유천동 100-1'));assert(!places.addressMatches('대전 중구 유천동 100-1','대전 중구 유천동'));});
test('변환 근거 주소를 변조하면 저장·연결 단계에서 거부',()=>{const r=places.geocode({capture:capture(),candidates:candidates()});r.geocodedAddress='대전 중구 유천로 36';assert.throws(()=>places.validate(r));});
test('좌표가 없는 검색 주소 항목도 주소 변환 가능',()=>{const c=capture();c.kind='address';c.placeID='';c.selectionKey='address:'+c.name.replace(/\s/g,'')+':'+c.address.replace(/\s/g,'');c.sourceURL='https://map.naver.com/p/';c.method='rendered_selected_address_panel';assert(places.geocode({capture:c,candidates:candidates()}).coordinate);});
test('주소 변환으로 얻은 좌표도 실제 정차 확인 전 배송계획 연결 금지',()=>{const c=places.geocode({capture:capture(),candidates:candidates()});assert.throws(()=>places.attach({plan:plan(),capture:c,targetID:'A',useCoordinate:true,curbConfirmed:false,requestAddress:c.roadAddress}),/정차 위치/);const r=places.attach({plan:plan(),capture:c,targetID:'A',useCoordinate:true,curbConfirmed:true,requestAddress:c.roadAddress});assert.deepEqual(r.plan.visits[0].tmapCoordinate.longitude,c.coordinate.longitude);});
test('캐시의 같은 주소 좌표는 재확인 시 동일 선택으로 인정',()=>{const c=places.geocode({capture:capture(),candidates:candidates()});assert(places.sameSelection({capture:c,fresh:copy(c),useCoordinate:true}).same);});
test('출발지와 최종 도착지를 배송 방문지와 독립적으로 선택',()=>{const p=plan(),r=endpoints(p);assert.equal(r.originName,'새 출발지');assert.equal(r.tmapOrigin.longitude,127.5);assert.equal(r.destination.name,'새 도착지');assert.equal(r.destination.tmapCoordinate.longitude,127.6);assert.equal(r.visits.length,2);assert.equal(p.originName,'맑은아침농산');});
test('최종 도착지 변경으로 출발·도착 구간과 티맵 바인딩 무효화',()=>{const p=plan();p.tmapBinding={visitIDs:['A','B']};p.legs.find(l=>l.fromID==='A'&&l.toID==='B').source='tmap';const r=endpoints(p);assert.equal(r.tmapBinding,null);assert(r.legs.filter(l=>l.fromID==='depot'||l.toID==='depot'||l.source==='tmap').every(l=>l.locationInvalidated));});
test('출발지 유지·복귀를 그대로 적용하면 기존 이동시간 보존',()=>{const p=plan(),r=endpoints(p,{originID:'current',endMode:'return'});assert.deepEqual(r.legs,p.legs);assert.equal(r.destination,null);assert.equal(r.originName,p.originName);});
test('목록에 없는 도착지와 좌표 미확인 장소는 선택 거부',()=>{assert.throws(()=>endpoints(plan(),{destinationID:'missing'}));const m=master();m[0].template.tmapCoordinate=null;m[0].capture=places.geocode({capture:capture(),candidates:candidates()});assert.throws(()=>places.endpoints({plan:plan(),customers:m,originID:'origin',endMode:'return'}),/정차 위치/);assert(places.endpoints({plan:plan(),customers:m,originID:'origin',endMode:'return',curbConfirmed:true}).tmapOrigin);});
test('티맵 요청의 시작·끝 좌표와 이름이 별도 선택한 장소로 전달',()=>{const p=endpoints(plan()),req=tmap.request({plan:p,options:{searchOption:'2',truckRouting:false}}),body=JSON.parse(req.body);assert.equal(body.startX,'127.5');assert.equal(body.endX,'127.6');assert.equal(decodeURIComponent(body.startName),'새 출발지');assert.equal(decodeURIComponent(body.endName),'새 도착지');assert.equal(body.viaPoints.length,2);assert.equal(req.endNodeID,'destination');});
test('30곳 배송에 별도 출발지·도착지가 있어도 배송 수는 30',()=>{const p=plan();p.visits=Array.from({length:30},(_,i)=>({...f.visit('v'+i),tmapCoordinate:{longitude:127.4,latitude:36.3}}));const r=endpoints(p),req=tmap.request({plan:r,options:{searchOption:'2',truckRouting:false}});assert.equal(req.apiID,30);assert.equal(JSON.parse(req.body).viaPoints.length,30);});
test('새 도착지 구간 없이 기존 회사 복귀 구간만으로 완료 계산 불가',()=>{const p=endpoints(plan());p.legs.forEach(l=>l.locationInvalidated=false);assert.notEqual(planner.solve(p).status,'candidate');p.legs.push(...p.visits.map(v=>({id:v.id+'-finish',fromID:v.id,toID:'destination',minutes:13,source:'manual'})));const r=planner.solve(p);assert.equal(r.status,'candidate',r.messages.join());assert.equal(r.returnMinutes,13);assert.equal(r.returnLegID,r.rows.at(-1).visitID+'-finish');});
function response(){const features=[];for(const [index,type,wire,coord] of [[1,'B1','1',[127.4,36.32]],[2,'B2','2',[127.41,36.32]],[3,'E','',[127.6,36.5]]]){features.push({properties:{index,pointType:type,viaPointId:wire},geometry:{type:'Point',coordinates:coord}},{properties:{index,pointType:type,viaPointId:wire,time:300,distance:1000,Fare:0},geometry:{type:'LineString',coordinates:[[127.5,36.4],coord]}});}return {features};}
test('티맵 E 구간은 새 도착지로 연결하고 배송 순번에 추가하지 않음',()=>{const p=endpoints(plan()),now=Date.now(),req=tmap.request({plan:p,options:{searchOption:'2',truckRouting:false}}),r=tmap.parse({response:response(),request:req,plan:p,now});assert.equal(r.rows.at(-1).visitID,'destination');assert.equal(r.legs.at(-1).tmapProvider.requestTo.longitude,127.6);const applied=tmap.apply({plan:p,route:r,now});assert.deepEqual(applied.tmapBinding.visitIDs,['A','B']);const solved=planner.solve(applied);assert.equal(solved.status,'candidate',solved.messages.join());assert.equal(solved.returnLegID,r.legs.at(-1).id);});
test('마지막 배송지 종료는 복귀 이동시간을 더하지 않고 티맵 요청 전 안내',()=>{const p=endpoints(plan(),{originID:'current',endMode:'last'});p.legs.forEach(l=>l.locationInvalidated=false);const r=planner.solve(p);assert.equal(r.status,'candidate');assert.equal(r.returnMinutes,0);assert.equal(r.finishMinute,r.lastWorkFinishMinute);assert.throws(()=>tmap.request({plan:p,options:{searchOption:'2',truckRouting:false}}),/최종 도착지/);});
test('운행 중 모든 배송 완료 뒤 실제 선택 도착지까지 이동하고 도착 기록',()=>{const c=f.config();c.columns=[f.column('R','rice20',0,0,'p1')];c.lots=[f.lot('P','R','rice20',2,'P','depot')];const p=f.plan([f.visit('P',{rice20:{pickup:2}})],c);p.originName='변경 출발지';p.destination={name:'다른 하차지'};p.legs.push({id:'P-finish',fromID:'P',toID:'destination',minutes:5,source:'demo'});const solved=planner.solve(p);assert.equal(solved.status,'candidate',solved.messages.join());let t=trip.create(p,solved,480,'test').trip;let serial=0;const apply=(type,minute,extra={})=>{t=trip.apply(t,{id:'e'+(++serial),type,minute,...extra}).trip;};apply('arrive',485);const report=()=>trip.report(trip.replay(t));apply('work',485,{endMinute:490,actions:report().suggestedActions});apply('complete',490);assert.throws(()=>apply('depart',490,{toID:'depot',legID:'P-depot'}));const remaining=trip.replan(t);assert.equal(remaining.returnLegID,'P-finish');apply('depart',490,{toID:'destination',legID:'P-finish'});apply('arrive',495);assert.equal(report().phase,'returned');assert.equal(report().currentID,'destination');apply('work',495,{endMinute:500,actions:[{lotID:'P',operation:'unload',quantity:2,columnID:'R',kind:'rice20'}]});assert.equal(report().positions.length,0);});
test('최종 도착지에도 도로 하역 조건 검증을 적용',()=>{const p=plan();p.destination={name:'끝'};p.road={enabled:true,requireCurb:true,requireHeight:false,requireClass1Toll:false};assert(roads.validate(p).some(x=>x.includes('끝')));});
const output={total:checks.length,passed:checks.filter(x=>x.passed).length,checks};fs.writeFileSync('evidence/endpoints_geocoding_tests.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output));if(output.total!==output.passed)process.exitCode=1;
