'use strict';
const assert=require('node:assert/strict'),api=require('../scripts/naver_api'),places=require('../scripts/naver_places');
const checks=[],copy=x=>JSON.parse(JSON.stringify(x)),now=Date.parse('2026-10-09T14:50:00Z');
function test(name,fn){try{fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.stack});}}
const response=()=>({items:[{title:'<b>가상</b> 거래처',roadAddress:'대전광역시 중구 유천로 35',address:'대전광역시 중구 유천동 100',mapx:'1273980000',mapy:'363160000',category:'배송>거래처',link:'https://business.example/'}]});
const capture=()=>api.seed({name:'가상 거래처',address:'대전 중구 유천로 35',now});
const maps=()=>({status:'OK',addresses:[{roadAddress:'대전광역시 중구 유천로 35',jibunAddress:'대전 중구 유천동 100',x:'127.398',y:'36.316'}]});
function gate(provider='search',extra={}){return {provider,key:provider==='search'?'search:'+'a'.repeat(64):'maps-free',ledger:{version:1,accounts:{}},now,freeConfirmed:true,...extra};}
test('지역 검색 WGS84 정수는 1천만으로 나누고 좌표를 지도 없이 반환',()=>{const r=api.local({response:response(),now})[0];assert.equal(r.capture.name,'가상 거래처');assert.equal(r.capture.coordinate.longitude,127.398);assert.equal(r.capture.coordinate.latitude,36.316);assert.equal(r.capture.placeID,'');assert.equal(r.capture.method,'naver_local_search');places.validate(r.capture);});
test('업체 홈페이지 링크를 네이버 장소 ID로 사용하지 않음',()=>{const r=api.local({response:response(),now})[0].capture;assert.match(r.sourceURL,/^https:\/\/map\.naver\.com\/p\/search\//);assert.equal(r.kind,'address');});
test('오래된 KATECH 예시 좌표를 추측해서 변환하지 않음',()=>{const r=response();r.items[0].mapx='311277';r.items[0].mapy='552097';assert.throws(()=>api.local({response:r,now}),/WGS84/);});
test('소수 WGS84를 지역 검색 정수로 착각하지 않음',()=>{const r=response();r.items[0].mapx='127.398';r.items[0].mapy='36.316';assert.throws(()=>api.local({response:r,now}));});
test('한국 범위 밖 좌표 거부',()=>{const r=response();r.items[0].mapx='-739800000';assert.throws(()=>api.local({response:r,now}));});
test('좌표 누락 결과가 저장 가능한 목록에 들어가지 않음',()=>{const r=response();delete r.items[0].mapy;assert.throws(()=>api.local({response:r,now}));});
test('정상 결과와 잘못된 결과를 섞으면 정상 좌표만 선택 가능',()=>{const r=response();r.items.push({...r.items[0],mapx:'311277'});assert.equal(api.local({response:r,now}).length,1);});
test('검색 결과 최대 5개 계약 위반 거부',()=>{const r=response();r.items=Array(6).fill(r.items[0]);assert.throws(()=>api.local({response:r,now}));});
test('빈 검색 결과 정상 처리',()=>assert.deepEqual(api.local({response:{items:[]},now}),[]));
test('검색 JSON 형태 불일치 거부',()=>assert.throws(()=>api.local({response:{items:{}},now})));
test('이름의 HTML과 문자 참조 해제',()=>{const r=response();r.items[0].title='<b>가상</b> &amp; &#44144;&#47000;';assert.equal(api.local({response:r,now})[0].capture.name,'가상 & 거래');});
test('Maps 좌표는 소수 WGS84이며 기존 장소 식별자 유지',()=>{const c={...capture(),kind:'place',placeID:'101',selectionKey:'place:101',sourceURL:'https://map.naver.com/p/entry/place/101',method:'rendered_selected_place_detail'};const r=api.geocode({capture:c,response:maps()});assert.equal(r.selectionKey,'place:101');assert.equal(r.coordinate.longitude,127.398);assert.equal(r.method,'naver_maps_geocoding');assert.equal(r.screenResolutionMeters,null);places.validate(r);});
test('건물 35와 350을 혼동하지 않음',()=>{const r=maps();r.addresses[0].roadAddress='대전 중구 유천로 350';assert.throws(()=>api.geocode({capture:capture(),response:r}),/건물 번호/);});
test('동일 도로라도 다른 도시 좌표 거부',()=>{const r=maps();r.addresses[0].roadAddress='서울 중구 유천로 35';assert.throws(()=>api.geocode({capture:capture(),response:r}));});
test('구 단위 대표 좌표를 건물 좌표로 쓰지 않음',()=>{const r=maps();r.addresses[0].roadAddress='대전 중구';assert.throws(()=>api.geocode({capture:capture(),response:r}));});
test('같은 주소의 상이한 좌표를 임의 선택하지 않음',()=>{const r=maps();r.addresses.push({...r.addresses[0],x:'127.4'});assert.throws(()=>api.geocode({capture:capture(),response:r}),/여러 좌표/);});
test('Maps 오류 상태 거부',()=>{const r=maps();r.status='INVALID_REQUEST';assert.throws(()=>api.geocode({capture:capture(),response:r}));});
test('주소 변환은 업체 이름을 바꾸지 않음',()=>{const c=capture();c.name='고객이 정한 이름';c.selectionKey='address:고객이정한이름:'+c.address.replace(/\s/g,'');const r=api.geocode({capture:c,response:maps()});assert.equal(r.name,c.name);});
test('전체 주소 없는 주소 변환 요청 거부',()=>assert.throws(()=>api.seed({name:'업체',address:'대전 중구',now})));
test('같은 이름·주소의 웹 장소와 API 결과는 중복 거래처로 판단',()=>{const c=capture(),r=api.local({response:response(),now})[0].capture;assert(places.customerMatches({first:c,second:r}));});
test('동명 다른 지점은 중복으로 판단하지 않음',()=>{const c=capture(),r=copy(c);r.roadAddress=r.address='대전 중구 유천로 350';assert(!places.customerMatches({first:c,second:r}));});
test('기존 선택 장소에 지역 검색 좌표를 붙여도 ID 유지',()=>{const c={...capture(),kind:'place',placeID:'101',selectionKey:'place:101',sourceURL:'https://map.naver.com/p/entry/place/101',method:'rendered_selected_place_detail'};const r=api.choose({capture:c,results:api.local({response:response(),now})});assert.equal(r.selectionKey,'place:101');});
test('지역 검색 자동 보완은 이름과 주소 모두 일치해야 함',()=>{const r=response();r.items[0].title='다른 거래처';assert.throws(()=>api.choose({capture:capture(),results:api.local({response:r,now})}));});
test('변조된 좌표·API 증거 불일치 거부',()=>{const c=api.local({response:response(),now})[0].capture;c.coordinate.longitude+=.01;assert.throws(()=>places.validate(c));});
test('변조된 API 주소 증거 거부',()=>{const c=api.geocode({capture:capture(),response:maps()});c.apiEvidence.roadAddress='대전 중구 유천로 350';assert.throws(()=>places.validate(c));});
test('검색 첫 요청은 25,000에서 24,999로 예약 차감',()=>{const r=api.reserve(gate());assert.equal(r.quota.used,1);assert.equal(r.quota.remaining,24999);});
test('검색 마지막 무료 요청 뒤 추가 예약 차단',()=>{let g=gate(),r=api.raise({...g,used:24999});r=api.reserve({...g,ledger:r.ledger});assert.equal(r.quota.remaining,0);assert.throws(()=>api.reserve({...g,ledger:r.ledger}),/무료 한도/);});
test('Maps 월 300만 번째 요청까지만 예약 허용',()=>{const g=gate('maps');let r=api.raise({...g,used:2999999});r=api.reserve({...g,ledger:r.ledger});assert.equal(r.quota.remaining,0);assert.throws(()=>api.reserve({...g,ledger:r.ledger}));});
test('Maps 무료 대표 계정 확인 전 호출 차단',()=>assert.throws(()=>api.reserve(gate('maps',{freeConfirmed:false})),/대표 계정/));
test('실패한 예약도 다음 요청에서 계속 사용량에 포함',()=>{const g=gate(),r=api.reserve(g);assert.equal(api.reserve({...g,ledger:r.ledger}).quota.used,2);});
test('외부 사용 횟수는 감소 보정할 수 없음',()=>{const g=gate(),r=api.raise({...g,used:10});assert.throws(()=>api.raise({...g,ledger:r.ledger,used:9}));});
test('외부 사용 횟수를 한도까지 반영하면 즉시 차단',()=>{const g=gate(),r=api.raise({...g,used:25000});assert.throws(()=>api.reserve({...g,ledger:r.ledger}));});
test('서버 한도 차단은 남은 로컬 횟수와 무관하게 유지',()=>{const g=gate(),r=api.block(g);assert.equal(r.quota.remaining,0);assert.throws(()=>api.reserve({...g,ledger:r.ledger}));});
test('검색 한도는 한국시간 다음 날 00:05에만 재개',()=>{const g=gate(),r=api.block(g);assert.throws(()=>api.reserve({...g,ledger:r.ledger,now:Date.parse('2026-10-09T15:04:59Z')}));const resumed=api.reserve({...g,ledger:r.ledger,now:Date.parse('2026-10-09T15:05:00Z')});assert.equal(resumed.quota.used,1);});
test('한도가 남아도 자정 5분 동안은 요청하지 않음',()=>assert.throws(()=>api.reserve(gate('search',{now:Date.parse('2026-10-09T15:02:00Z')})),/00:05/));
test('Maps 월 한도는 다음 날에 초기화되지 않음',()=>{const g=gate('maps'),r=api.block(g);assert.throws(()=>api.reserve({...g,ledger:r.ledger,now:Date.parse('2026-10-10T00:00:00Z')}));});
test('Maps 월 한도는 다음 달 1일 00:05에 재개',()=>{const g=gate('maps'),r=api.block(g);assert.throws(()=>api.reserve({...g,ledger:r.ledger,now:Date.parse('2026-10-31T15:04:59Z')}));assert.equal(api.reserve({...g,ledger:r.ledger,now:Date.parse('2026-10-31T15:05:00Z')}).quota.used,1);});
test('Maps 앱 키를 바꾸어도 계정 공유 카운터 유지',()=>{const g=gate('maps'),r=api.raise({...g,used:100});assert.equal(api.refresh({...g,ledger:r.ledger}).quota.used,100);});
test('같은 검색 Client ID의 비밀키 회전으로 한도를 초기화하지 않음',()=>{const g=gate(),r=api.raise({...g,used:100});assert.equal(api.refresh({...g,ledger:r.ledger}).quota.used,100);});
test('다른 검색 Client ID 기록도 같은 보관함에 보존',()=>{const g=gate(),r=api.reserve(g),other=api.reserve({...g,ledger:r.ledger,key:'search:'+'b'.repeat(64)});assert.equal(Object.keys(other.ledger.accounts).length,2);assert.equal(other.ledger.accounts[g.key].used,1);});
test('과거 시간으로 한도 재설정 시도 차단',()=>{const g=gate(),r=api.reserve(g);assert.throws(()=>api.reserve({...g,ledger:r.ledger,now:now-3600000}),/오래/);});
test('손상된 사용량 기록에서 호출 차단',()=>{const g=gate(),r=api.reserve(g);r.ledger.accounts[g.key].used=-1;assert.throws(()=>api.reserve({...g,ledger:r.ledger}));});
test('잘못된 제공자 또는 계정 키 거부',()=>{assert.throws(()=>api.reserve(gate('search',{key:'maps-free'})));assert.throws(()=>api.reserve(gate('wrong')));});
test('JSCore용 JSON 호출은 실패 사유를 반환',()=>{const r=JSON.parse(api.reserveJSON(JSON.stringify(gate('maps',{freeConfirmed:false}))));assert.equal(r.ok,false);assert.match(r.message,/대표 계정/);});
const report={passed:checks.filter(x=>x.passed).length,total:checks.length,checks};console.log(JSON.stringify(report));if(report.passed!==report.total)process.exitCode=1;
