// Generated by scripts/embed_capture_script.py
enum VehicleProfileScript {
    static let source = #"""
    () => {
      // Only rendered controls in the vehicle dialog; no internal state or network.
      const tidy=x=>String(x||'').replace(/\s+/g,' ').trim();
      const shown=e=>!!e&&e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).display!=='none';
      const dialogs=[...document.querySelectorAll('dialog,[role="dialog"]')].filter(shown);
      const d=dialogs.find(e=>tidy(e.innerText||e.textContent).includes('차종/연료 설정'));
      if(!d||dialogs.length!==1)return null;
      const choices=[...d.querySelectorAll('input[name="checkbox_car"]')].filter(e=>e.checked);
      if(choices.length!==1)return null;
      const vehicleClass=tidy(choices[0].parentElement.innerText||choices[0].parentElement.textContent).match(/^[1-5]종(?:\(경차\))?/)?.[0]||null;
      const input=[...d.querySelectorAll('input[type="text"]')].find(e=>tidy(e.closest('label')?.textContent).startsWith('높이 제한'));
      let heightMM=null;
      if(input){
        const group=input.closest('li')?.parentElement;
        const presets=group?[...group.querySelectorAll('button.option_button.on')].filter(shown):[];
        const custom=tidy(input.value);
        if(presets.length===1&&!custom){
          const m=tidy(presets[0].innerText||presets[0].textContent).match(/^(\d+(?:\.\d+)?)m$/);
          if(m)heightMM=Math.round(Number(m[1])*1000);
        }else if(!presets.length&&/^\d+(?:\.\d+)?$/.test(custom))heightMM=Math.round(Number(custom)*1000);
      }
      return {vehicleClass,heightMM,source:'saved_dialog_reopen'};
    }
    """#
}
enum PeekVehicleScript {
    static let source = #"""
    async (readerSource, profileSource) => {
      const read=(0,eval)('('+readerSource+')'),profile=(0,eval)('('+profileSource+')');
      const shown=e=>!!e&&e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).display!=='none';
      const text=e=>String(e?.innerText||e?.textContent||'').replace(/\s+/g,' ').trim();
      const dialogs=()=>[...document.querySelectorAll('dialog,[role="dialog"]')].filter(shown);
      const stable=c=>JSON.stringify([c.mode,c.routePoints,c.vehicleClass,c.candidates,c.detail,c.departureTimeLabel]);
      const before=JSON.parse(read());
      if(!before.quality.readyForSummaryImport||!before.detail.matchesSelected||dialogs().length)return JSON.stringify(before);
      const button=[...document.querySelectorAll('[role="tabpanel"] button')].filter(shown).find(e=>/차량 기준$/.test(text(e)));
      if(!button)return JSON.stringify(before);
      const until=async fn=>{for(let i=0;i<16;i++){const v=fn();if(v)return v;await new Promise(resolve=>setTimeout(resolve,125));}return null;};
      let opened=null,observed=null;
      try{
        // Ordinary visible UI actions. Opening then closing does not save changes.
        button.click();
        opened=await until(()=>dialogs().find(d=>text(d).includes('차종/연료 설정')));
        if(!opened)throw Error('차량 설정창을 확인하지 못했습니다.');
        observed=profile();
      }finally{
        if(opened){const close=opened.querySelector('button.btn_close');if(close)close.click();}
      }
      if(!await until(()=>dialogs().length===0))throw Error('차량 설정창을 닫은 뒤 다시 읽어 주세요.');
      const after=JSON.parse(read());
      if(!after.quality.readyForSummaryImport||stable(before)!==stable(after))throw Error('차량 설정을 확인하는 동안 경로가 바뀌었습니다. 다시 읽어 주세요.');
      if(observed&&observed.vehicleClass===after.vehicleClass)after.observedVehicleSettings={...observed,confirmed:true};
      return JSON.stringify(after);
    }
    """#
}
enum BikeEndpointScript {
    static let source = #"""
    (scopeOnly = false) => {
      // Read rendered DOM/SVG/raster tile placement only. No map SDK, fetch,
      // panorama coordinates, private page state or guessed POI-to-entrance offset.
      const tidy=x=>String(x||'').replace(/\s+/g,' ').trim();
      const text=e=>tidy(e?.innerText||e?.textContent);
      const all=(r,s)=>Array.from(r.querySelectorAll(s));
      const shown=e=>!!e&&e.getClientRects().length>0&&getComputedStyle(e).display!=='none'&&getComputedStyle(e).visibility!=='hidden';
      const out=(phase,message,extra={})=>JSON.stringify({ok:phase==='ready',phase,message,...extra});
      const url=location.href;
      const m=/^https:\/\/map\.naver\.com\/p\/directions\/([^/?#]+)\/([^/?#]+)\/-\/bike(?:\/(\d+))?(?:\?[^#]*)?$/.exec(url);
      if(!m)return out('blocked','경유지 없는 자전거 길찾기 결과를 먼저 열어 주세요.');
      const point=raw=>{const p=raw.split(',');if(p.length!==5)return null;try{const name=decodeURIComponent(p[2]);p[2]=encodeURIComponent(name);return{token:p.join(','),name};}catch(_){return null;}};
      const start=point(m[1]),destination=point(m[2]);
      if(!start?.name||!destination?.name)return out('blocked','출발·목적지 주소를 해석하지 못했습니다.');
      const routeKey=start.token+'/'+destination.token+'/bike';
      const base={routeKey,sourceURL:url,start,destination};
      const fail=(phase,message,extra={})=>out(phase,message,{...base,...extra});
      if(all(document,'dialog,[role="dialog"]').some(shown))return fail('blocked','열린 지도 설정창을 닫아 주세요.');
      const tabs=all(document,'[role="tab"][aria-selected="true"]').filter(shown);
      const inputs=all(document,'input[role="combobox"]').filter(shown).map(e=>tidy(e.value));
      if(tabs.length!==1||text(tabs[0])!=='자전거'||inputs.length!==2||inputs[0]!==tidy(start.name)||inputs[1]!==tidy(destination.name))return fail('blocked','입력한 장소와 표시된 자전거 경로가 일치하지 않습니다. 길찾기를 다시 실행해 주세요.');
      const cards=all(document,'[role="tabpanel"] [aria-pressed="true"]').filter(e=>shown(e)&&e.querySelector('.direction_top_area'));
      if(cards.length!==1)return fail('blocked','자전거 경로 한 개가 선택된 결과가 필요합니다.');
      const summary=e=>text(e?.querySelector('.direction_top_area'))+'|'+text(e?.querySelector('.bike_route_order_list'));
      const card=cards[0], selection=summary(card);
      if(!selection.includes('자전거 경로'))return fail('blocked','자전거 경로 요약을 확인하지 못했습니다.');
      const common={...base,selection,selectedIndex:m[3]===undefined?0:+m[3]};
      if(scopeOnly)return JSON.stringify({ok:true,...common});
      const result=(phase,message,extra={})=>out(phase,message,{...common,...extra});
      const detail=document.querySelector('#sub_panel');
      if(!shown(detail)||!detail.querySelector('.direction_guide_list'))return result('detail','자전거 상세 안내를 여는 중입니다.');
      if(summary(detail)!==selection||card.getAttribute('aria-expanded')!=='true')return result('blocked','선택한 경로와 상세 안내가 다릅니다.');
      const rows=all(detail,'.direction_guide_item');
      const starts=rows.filter(e=>e.querySelector('.direction_tbt_icon img[alt="출발지"]'));
      const goals=rows.filter(e=>e.querySelector('.direction_tbt_icon img[alt="목적지"]'));
      if(starts.length!==1||text(starts[0].querySelector('.btn_direction strong'))!==tidy(start.name))return result('blocked','출발지 상세 안내가 현재 검색과 다릅니다.');
      if(!goals.length)return result('arrival','마지막 도착 안내를 불러오는 중입니다.');
      if(goals.length!==1||goals[0]!==rows[rows.length-1]||text(goals[0].querySelector('.btn_direction strong'))!==tidy(destination.name))return result('blocked','목적지 상세 안내를 확정하지 못했습니다.');
      if(!goals[0].querySelector('.btn_direction.is_selected'))return result('focus','도착 위치로 지도를 이동하는 중입니다.');
      const c=url.match(/[?&]c=([^&]+)/)?.[1]?.split(',');
      if(!c||c.length<4||c.slice(1,4).some(x=>!/^0(?:\.0+)?$/.test(x)))return result('blocked','회전·기울임 없는 일반 지도로 표시해 주세요.');
      const maps=all(document,'[role="application"]').filter(shown);
      if(maps.length!==1)return result('blocked','지도 화면을 하나로 확인하지 못했습니다.');
      const map=maps[0], rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};};
      const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
      // Only the observed absolute M/L path format is accepted; curves, multiple
      // subpaths and transformed paths fail closed instead of guessing an end.
      const parsePath=d=>{
        if(!/^\s*M\s*[-\d.,\s]+L\s*[-\d.,\s]+\s*$/.test(d||''))return null;
        const v=d.match(/-?\d+(?:\.\d+)?/g)?.map(Number);
        if(!v||v.length<4||v.length%2||v.some(x=>!Number.isFinite(x)))return null;
        return Array.from({length:v.length/2},(_,i)=>({x:v[i*2],y:v[i*2+1]}));
      };
      const axisAligned=e=>{
        for(let node=e;node&&node!==map.parentElement;node=node.parentElement){
          const t=getComputedStyle(node).transform;
          if(!t||t==='none')continue;
          const a=t.match(/^matrix\(([^)]+)\)$/)?.[1].split(',').map(Number);
          const b=t.match(/^matrix3d\(([^)]+)\)$/)?.[1].split(',').map(Number);
          if(a&&a.length===6&&a.every(Number.isFinite)&&a[0]>0&&a[3]>0&&Math.abs(a[1])+Math.abs(a[2])<1e-7)continue;
          if(b&&b.length===16&&b.every(Number.isFinite)&&b[0]>0&&b[5]>0&&b[10]===1&&b[15]===1&&[1,2,3,4,6,7,8,9,11,14].every(i=>Math.abs(b[i])<1e-7))continue;
          return false;
        }return true;
      };
      const paths=[];
      for(const svg of all(map,'svg')){
        if(!shown(svg)||!axisAligned(svg))continue;
        const vb=(svg.getAttribute('viewBox')||'').trim().split(/[ ,]+/).map(Number),r=rect(svg);
        if(vb.length!==4||vb.some(x=>!Number.isFinite(x))||vb[2]<=0||vb[3]<=0||r.width<=0||r.height<=0||Math.abs(r.width/vb[2]-r.height/vb[3])>1e-5)continue;
        for(const p of all(svg,'path')){
          const style=(p.getAttribute('style')||'').replace(/\s/g,'').toLowerCase(),v=parsePath(p.getAttribute('d'));
          if(!v||p.hasAttribute('transform')||!shown(p))continue;
          paths.push({d:p.getAttribute('d'),style,points:v.map(p=>({x:r.x+(p.x-vb[0])*r.width/vb[2],y:r.y+(p.y-vb[1])*r.height/vb[3]}))});
        }
      }
      const solid=paths.filter(p=>p.style.includes('stroke:#076cf2;')&&p.style.includes('stroke-width:9px;')&&!p.style.includes('stroke-dasharray'));
      const outlines=paths.filter(p=>p.style.includes('stroke:#04459b;')&&p.style.includes('stroke-width:12px;'));
      if(solid.length!==1||outlines.length!==1||solid[0].d!==outlines[0].d)return result('blocked','자전거 경로 선을 하나로 구분하지 못했습니다. 일반 지도에서 다시 읽어 주세요.');
      const line=solid[0],first=line.points[0],end=line.points[line.points.length-1];
      if(distance(end,outlines[0].points.at(-1))>0.5)return result('blocked','지도 경로 선이 아직 이동 중입니다.');
      const markers=all(map,'.DIRECTIONS_PIN_MARKER [data-maps-overlay]');
      const marker=label=>{const xs=markers.filter(e=>text(e)===label);return xs.length===1?rect(xs[0]):null;};
      const startPin=marker('출발'),goalPin=marker('도착');
      if(!startPin||!goalPin)return result('blocked','출발·도착 표시를 확인하지 못했습니다.');
      const connectors=paths.filter(p=>p.style.includes('stroke:#a7b0be;')&&p.style.includes('stroke-dasharray:1,12;'));
      const connects=(a,b)=>distance(a,b)<=1.5||connectors.some(p=>(distance(a,p.points[0])<=1.5&&distance(b,p.points.at(-1))<=1.5)||(distance(b,p.points[0])<=1.5&&distance(a,p.points.at(-1))<=1.5));
      if(!connects(first,startPin)||!connects(end,goalPin))return result('blocked','경로 선의 끝과 목적지 연결선을 함께 확인하지 못했습니다.');
      const mr=rect(map);
      if(end.x<Math.max(0,mr.x)||end.y<Math.max(0,mr.y)||end.x>Math.min(innerWidth,mr.x+mr.width)||end.y>Math.min(innerHeight,mr.y+mr.height))return result('focus','도착 경로의 끝이 보이도록 지도를 이동합니다.');
      const hit=document.elementFromPoint(end.x,end.y);
      if(!hit||!map.contains(hit))return result('blocked','도착 위치가 패널에 가려져 있습니다. 지도를 넓게 표시한 후 다시 읽어 주세요.');
      const tiles=[];
      for(const image of all(map,'img')){
        if(!shown(image)||!axisAligned(image))continue;
        const src=image.getAttribute('src')||'',t=/^https:\/\/map\.pstatic\.net\/nrb\/styles\/basic\/\d+\/(\d+)\/(\d+)\/(\d+)\.png(?:\?[^#]*)?$/.exec(src),r=rect(image);
        if(!t||r.width<64||r.width>1024||Math.abs(r.width-r.height)>0.01)continue;
        const z=+t[1],x=+t[2],y=+t[3],n=2**z;
        if(z<0||z>23||x>=n||y>=n)continue;
        tiles.push({z,x,y,r});
      }
      const z=Math.max(...tiles.map(t=>t.z));
      if(!Number.isFinite(z))return result('blocked','화면에 표시된 일반 지도 조각을 읽지 못했습니다.');
      if(z<19)return result('zoom','도착 경로의 끝을 확대하는 중입니다.',{tileZoom:z});
      const ts=tiles.filter(t=>t.z===z),n=2**z;
      if(ts.length<3||new Set(ts.map(t=>t.x)).size<2||new Set(ts.map(t=>t.y)).size<2)return result('blocked','좌표를 교차 확인할 지도 조각이 부족합니다.');
      const origins=ts.map(t=>({x:t.r.x-t.x*t.r.width,y:t.r.y-t.y*t.r.height})),origin=origins[0],width=ts[0].r.width;
      if(ts.some(t=>Math.abs(t.r.width-width)>0.01)||origins.some(o=>distance(o,origin)>0.75))return result('blocked','지도 조각 위치가 서로 다릅니다. 확대가 끝난 뒤 다시 읽어 주세요.');
      const half=20037508.342789244,nx=(end.x-origin.x)/(width*n),ny=(end.y-origin.y)/(width*n);
      const mercatorX=(nx*2-1)*half,mercatorY=(1-ny*2)*half;
      const longitude=mercatorX/half*180,latitude=Math.atan(Math.sinh(mercatorY/6378137))*180/Math.PI;
      if(!(longitude>=124&&longitude<=132&&latitude>=32&&latitude<=40))return result('blocked','계산한 좌표가 국내 지도 범위를 벗어납니다.');
      const metersPerPixel=2*half/(width*n)*Math.cos(latitude*Math.PI/180);
      const name=destination.name+' · 자전거 종점';
      const endpoint={token:mercatorX.toFixed(3)+','+mercatorY.toFixed(3)+','+encodeURIComponent(name)+',,SIMPLE_POI',name};
      const arrivalSideText=text(goals[0].querySelector('.btn_direction_detail_goal_desc'));
      return result('ready','자전거 경로 선의 끝점을 읽었습니다.',{
        capture:{version:1,sourceURL:url,routeKey,selectedIndex:common.selectedIndex,start,destination,point:endpoint,
          latitude,longitude,mercatorX,mercatorY,tileZoom:z,screenResolutionMeters:metersPerPixel*2,
          destinationGapMeters:distance(end,goalPin)*metersPerPixel,arrivalSideText,
          detailSummary:selection,finalInstruction:text(rows[rows.length-2]?.querySelector('.btn_direction strong')),
          guideCount:rows.length,capturedAt:new Date().toISOString(),method:'rendered_svg_and_tiles',
          previewURL:'https://map.naver.com/p/directions/'+start.token+'/'+endpoint.token+'/-/bike?c=18.00,0,0,0,dh'},
        screenPoint:end,tileZoom:z
      });
    }
    """#
}
enum PrepareBikeEndpointScript {
    static let source = #"""
    async readerSource => {
      // Only visible UI controls: detail, guide scrolling, arrival, zoom.
      const read=(0,eval)('('+readerSource+')');
      const shown=e=>!!e&&e.getClientRects().length>0&&getComputedStyle(e).display!=='none'&&getComputedStyle(e).visibility!=='hidden';
      const text=e=>String(e?.innerText||e?.textContent||'').replace(/\s+/g,' ').trim();
      const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
      let before=JSON.parse(read());
      if(before.phase==='blocked')throw Error(before.message);
      const key=before.routeKey,selection=before.selection,index=before.selectedIndex;
      const check=()=>{
        const s=JSON.parse(read());
        if(s.routeKey!==key||s.selection!==selection||s.selectedIndex!==index)throw Error('읽는 동안 목적지나 자전거 경로가 바뀌었습니다. 다시 읽어 주세요.');
        return s;
      };
      let previous=null,actions=0,scrolls=0,focuses=0,zooms=0;
      for(let pass=0;pass<65;pass++){
        const s=check();
        if(s.ok){
          const signature=JSON.stringify([s.capture.point.token,s.capture.detailSummary,s.capture.tileZoom,s.capture.destinationGapMeters,s.screenPoint]);
          if(previous===signature)return JSON.stringify(s.capture);
          previous=signature;await pause(250);continue;
        }
        previous=null;
        // Transient geometry states get a bounded retry, not a made-up coordinate.
        if(s.phase==='blocked'){
          if(pass>0&&pass<64){await pause(200);continue;}
          throw Error(s.message);
        }
        if(s.phase==='detail'){
          const card=[...document.querySelectorAll('[role="tabpanel"] [aria-pressed="true"]')].find(e=>shown(e)&&e.querySelector('.direction_top_area'));
          const button=card?.querySelector('.btn_way_detail');
          if(!button||actions++>2)throw Error('자전거 상세보기를 열지 못했습니다.');
          button.click();
        }else if(s.phase==='arrival'){
          const rows=[...document.querySelectorAll('#sub_panel .direction_guide_item')];
          if(!rows.length||scrolls++>=22)throw Error('마지막 도착 안내를 불러오지 못했습니다. 상세 안내의 맨 아래로 이동한 뒤 다시 읽어 주세요.');
          rows.at(-1).scrollIntoView({block:'center',behavior:'instant'});
        }else if(s.phase==='focus'){
          const row=[...document.querySelectorAll('#sub_panel .direction_guide_item')].find(e=>e.querySelector('.direction_tbt_icon img[alt="목적지"]'));
          const button=row?.querySelector('.btn_direction');
          if(!button||focuses++>=3)throw Error('지도에서 도착 경로의 끝이 보이도록 이동해 주세요.');
          button.click();
        }else if(s.phase==='zoom'){
          const buttons=[...document.querySelectorAll('button')].filter(e=>shown(e)&&text(e)==='확대');
          if(buttons.length!==1||buttons[0].disabled||zooms++>=8)throw Error('입구를 읽을 만큼 지도를 확대하지 못했습니다.');
          buttons[0].click();
        }else throw Error('지도 화면의 단계를 확인하지 못했습니다.');
        await pause(350);
      }
      throw Error('지도 이동이 안정되지 않아 종점을 저장하지 않았습니다. 다시 읽어 주세요.');
    }
    """#
}
enum NaverPlaceRootScript {
    static let source = #"""
    function readNaverPlaceRoot() {
      'use strict';
      const tidy=x=>String(x||'').replace(/\s+/g,' ').trim();
      const out=x=>JSON.stringify(x);
      const blocked=message=>out({ok:false,message});
      const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};};
      const shown=e=>{
        if(!e||!e.getClientRects().length)return false;
        for(let p=e;p&&p.nodeType===1;p=p.parentElement){const s=getComputedStyle(p);if(s.display==='none'||s.visibility==='hidden'||s.visibility==='collapse'||s.opacity==='0')return false;}
        return true;
      };
      const axisAligned=e=>{
        for(let p=e;p&&p.nodeType===1;p=p.parentElement){
          const t=getComputedStyle(p).transform||'none';if(t==='none')continue;
          let m=/^matrix\(([^)]+)\)$/.exec(t);
          if(m){const v=m[1].split(',').map(Number);if(v.length!==6||v.some(x=>!Number.isFinite(x))||Math.abs(v[1])>1e-6||Math.abs(v[2])>1e-6||v[0]<=0||v[3]<=0)return false;continue;}
          m=/^matrix3d\(([^)]+)\)$/.exec(t);
          if(m){const v=m[1].split(',').map(Number);if(v.length!==16||v.some(x=>!Number.isFinite(x))||v[0]<=0||v[5]<=0||v[10]!==1||v[15]!==1||[1,2,3,4,6,7,8,9,11].some(i=>Math.abs(v[i])>1e-6))return false;continue;}
          return false;
        }
        return true;
      };
      let url;try{url=new URL(location.href);}catch(_){return blocked('네이버 지도에서 장소나 주소를 선택해 주세요.');}
      if(url.protocol!=='https:'||url.hostname!=='map.naver.com')return blocked('네이버 지도에서 장소나 주소를 선택해 주세요.');
      if([...document.querySelectorAll('input[role="combobox"]')].some(e=>shown(e)&&e.getAttribute('aria-expanded')==='true'))return blocked('검색어 입력을 마치고 결과의 장소를 선택한 뒤 읽어 주세요.');
      const maps=[...document.querySelectorAll('.mantle_map')].filter(shown);
      if(maps.length!==1)return blocked('일반 지도와 선택 장소의 표식을 표시해 주세요.');
      const map=maps[0],pins=[...map.querySelectorAll('.ENTRY_MARKER [data-maps-overlay]')].filter(e=>shown(e.querySelector('.marker_icon_image_wrap')));
      if(pins.length!==1)return blocked('검색 또는 저장 목록에서 장소 하나를 선택해 주세요.');
      const pin=pins[0],markerName=tidy(pin.querySelector('.marker_title')?.textContent);
      if(!markerName)return blocked('선택한 지도 표식의 이름을 읽지 못했습니다.');
      let kind='',placeID='',name=markerName,frameURL='',address='',roadAddress='',jibunAddress='';
      const frame=document.querySelector('#entryIframe');
      if(frame&&shown(frame)){
        let f;try{f=new URL(frame.getAttribute('src')||'',url.href);}catch(_){return blocked('선택 장소의 상세 화면을 기다린 뒤 다시 읽어 주세요.');}
        const m=/^\/place\/(\d+)(?:\/|$)/.exec(f.pathname);
        if(f.protocol!=='https:'||f.hostname!=='pcmap.place.naver.com'||!m)return blocked('선택한 장소 상세 화면을 읽지 못했습니다.');
        const selected=/\/entry\/place\/(\d+)(?:\/|$)/.exec(url.pathname);
        if(selected&&selected[1]!==m[1])return blocked('지도와 상세 패널의 장소가 다릅니다. 잠시 뒤 다시 읽어 주세요.');
        kind='place';placeID=m[1];frameURL=f.href;
      }else{
        const titles=[...document.querySelectorAll('.address_info_area .address_title')].filter(shown);
        if(titles.length!==1)return blocked('선택 장소의 상세 정보 또는 주소 패널을 열어 주세요.');
        const panel=titles[0].closest('.scroll_box')||titles[0].closest('.scroll_area');
        const names=panel?[...panel.querySelectorAll('.title_box .title')].filter(shown):[];
        if(names.length!==1)return blocked('주소 검색 결과를 하나로 구분하지 못했습니다.');
        kind='address';name=tidy(names[0].textContent);address=roadAddress=tidy(titles[0].textContent);
        if(!name.replace(/\s/g,'').includes(markerName.replace(/\s/g,'')))return blocked('주소 패널과 지도 표식이 다릅니다. 주소를 다시 선택해 주세요.');
        const labels=[...panel.querySelectorAll('.label_address_land')];
        if(labels.length===1){const row=labels[0].parentElement.cloneNode(true);row.querySelectorAll('.label_address_land,button,a,[role="button"]').forEach(e=>e.remove());jibunAddress=tidy(row.textContent);}
      }
      const selectionKey=kind==='place'?'place:'+placeID:'address:'+name.replace(/\s/g,'')+':'+address.replace(/\s/g,'');
      const base={ok:true,message:'선택 장소를 읽었습니다.',kind,selectionKey,placeID,name,frameURL,address,roadAddress,jibunAddress,
        sourceURL:kind==='place'?'https://map.naver.com/p/entry/place/'+placeID:url.origin+url.pathname,
        coordinate:null,mercatorX:null,mercatorY:null,tileZoom:null,screenResolutionMeters:null,point:null,coordinateIssue:''};
      const partial=message=>out({...base,coordinateIssue:message});
      const view=(url.searchParams.get('c')||'').split(',');
      if(view.length&&view.length!==1&&(!view.slice(0,4).every(x=>Number.isFinite(Number(x)))||Number(view[1])!==0||Number(view[2])!==0))return partial('지도의 회전·기울기를 해제하고 다시 읽으면 좌표를 가져올 수 있습니다.');
      if(!axisAligned(pin)||!axisAligned(map))return partial('지도 회전이나 변형이 있어 좌표를 확정하지 않았습니다.');
      const p=rect(pin),mr=rect(map);
      if(p.width!==0||p.height!==0)return partial('선택 표식의 기준점 구조가 달라 좌표를 확정하지 않았습니다.');
      if(p.x<Math.max(mr.x,0)||p.y<Math.max(mr.y,0)||p.x>Math.min(mr.x+mr.width,innerWidth)||p.y>Math.min(mr.y+mr.height,innerHeight))return partial('선택 표식이 화면에 보이도록 지도를 이동한 뒤 다시 읽어 주세요.');
      const hit=document.elementFromPoint(p.x,p.y);
      if(!hit||!map.contains(hit))return partial('선택 표식이 패널에 가려져 있습니다. 지도를 넓게 표시한 뒤 다시 읽어 주세요.');
      const tiles=[];
      for(const image of map.querySelectorAll('img')){
        if(!shown(image))continue;
        const t=/^https:\/\/map\.pstatic\.net\/nrb\/styles\/basic\/\d+\/(\d+)\/(\d+)\/(\d+)\.png(?:\?[^#]*)?$/.exec(image.getAttribute('src')||''),r=rect(image);
        if(!t)continue;
        if(!axisAligned(image)||r.width<64||r.width>1024||Math.abs(r.width-r.height)>0.01)return partial('지도 조각의 변형이 있어 좌표를 확정하지 않았습니다. 이동이 끝난 뒤 다시 읽어 주세요.');
        if(r.x+r.width<Math.max(mr.x,0)||r.y+r.height<Math.max(mr.y,0)||r.x>Math.min(mr.x+mr.width,innerWidth)||r.y>Math.min(mr.y+mr.height,innerHeight))continue;
        const z=+t[1],x=+t[2],y=+t[3],n=2**z;if(z<0||z>23||x>=n||y>=n)return partial('지도 조각 번호가 맞지 않아 좌표를 확정하지 않았습니다.');
        tiles.push({z,x,y,r});
      }
      if(tiles.length<3||new Set(tiles.map(t=>t.z)).size!==1||new Set(tiles.map(t=>t.x)).size<2||new Set(tiles.map(t=>t.y)).size<2)return partial('일반 지도 조각을 충분히 읽지 못했습니다. 확대·이동이 끝난 뒤 다시 읽어 주세요.');
      const z=tiles[0].z,width=tiles[0].r.width,n=2**z,origin={x:tiles[0].r.x-tiles[0].x*width,y:tiles[0].r.y-tiles[0].y*width};
      if(tiles.some(t=>Math.abs(t.r.width-width)>0.01||Math.hypot(t.r.x-t.x*width-origin.x,t.r.y-t.y*width-origin.y)>0.75))return partial('지도 조각 위치가 맞지 않습니다. 지도 이동이 끝난 뒤 다시 읽어 주세요.');
      const half=20037508.342789244,nx=(p.x-origin.x)/(width*n),ny=(p.y-origin.y)/(width*n),mercatorX=(nx*2-1)*half,mercatorY=(1-ny*2)*half;
      const longitude=nx*360-180,latitude=Math.atan(Math.sinh(Math.PI*(1-2*ny)))*180/Math.PI;
      const resolution=2*half*Math.cos(latitude*Math.PI/180)/(width*n)*2;
      if(!Number.isFinite(longitude)||!Number.isFinite(latitude)||longitude<124||longitude>132||latitude<32||latitude>40)return partial('표식 좌표가 국내 지도 범위를 벗어나 가져오지 않았습니다.');
      if(resolution>5)return partial('좌표 판독을 위해 지도를 더 확대한 뒤 다시 읽어 주세요.');
      base.coordinate={longitude,latitude};base.mercatorX=mercatorX;base.mercatorY=mercatorY;base.tileZoom=z;base.screenResolutionMeters=resolution;
      base.point={name,token:mercatorX.toFixed(3)+','+mercatorY.toFixed(3)+','+encodeURIComponent(name)+',,SIMPLE_POI'};
      return out(base);
    }
    """#
}
enum NaverPlaceDetailScript {
    static let source = #"""
    function readNaverPlaceDetail() {
      'use strict';
      const tidy=x=>String(x||'').replace(/\s+/g,' ').trim();
      const shown=e=>{if(!e||!e.getClientRects().length)return false;for(let p=e;p&&p.nodeType===1;p=p.parentElement){const s=getComputedStyle(p);if(s.display==='none'||s.visibility==='hidden'||s.opacity==='0')return false;}return true;};
      let url;try{url=new URL(location.href);}catch(_){return JSON.stringify({ok:false,message:'장소 상세 화면을 읽지 못했습니다.'});}
      const id=/^\/place\/(\d+)(?:\/|$)/.exec(url.pathname);
      if(url.protocol!=='https:'||url.hostname!=='pcmap.place.naver.com'||!id)return JSON.stringify({ok:false,message:'네이버 장소 상세 화면에서 읽어 주세요.'});
      const names=[...document.querySelectorAll('.IY7ZX')].filter(shown);
      const name=names.length===1?tidy(names[0].textContent):tidy([...document.querySelectorAll('h1')].find(shown)?.textContent);
      if(!name)return JSON.stringify({ok:false,message:'장소 이름이 표시된 홈·정보 화면을 열고 다시 읽어 주세요.'});
      const labels=[...document.querySelectorAll('strong')].filter(e=>tidy(e.textContent)==='주소');
      let address='',roadAddress='',jibunAddress='';
      if(labels.length===1){
        const row=labels[0].parentElement;
        const first=[...row.querySelectorAll('.pz7wy')].find(shown);address=tidy(first?.textContent);
        for(const label of row.querySelectorAll('.TjXg1')){
          if(!shown(label))continue;
          const key=tidy(label.textContent),copy=label.parentElement.cloneNode(true);
          copy.querySelectorAll('.TjXg1,.S8peq,a,button').forEach(e=>e.remove());
          if(key==='도로명')roadAddress=tidy(copy.textContent);
          if(key==='지번')jibunAddress=tidy(copy.textContent);
        }
      }
      return JSON.stringify({ok:true,placeID:id[1],name,address,roadAddress,jibunAddress});
    }
    """#
}
