// Generated by scripts/embed_capture_script.py
enum NaverPlaceEngineSource {
    static let source = #"""
    /* Selected public Naver place metadata and explicit plan attachment. No network. */
    var DeliveryNaverPlaces=(function(){
      'use strict';
      const copy=x=>JSON.parse(JSON.stringify(x)),tidy=x=>String(x||'').replace(/\s+/g,' ').trim();
      const fail=m=>{throw Error(m);},sameName=(a,b)=>tidy(a).replace(/\s/g,'')===tidy(b).replace(/\s/g,'');
      const coordinate=c=>c&&typeof c.longitude==='number'&&typeof c.latitude==='number'&&Number.isFinite(c.longitude)&&Number.isFinite(c.latitude)&&c.longitude>=124&&c.longitude<=132&&c.latitude>=32&&c.latitude<=40;
      function text(value,max,label){if(typeof value!=='string'||value.length>max||/[\x00-\x1f\x7f]/.test(value))fail(label+' 형식을 확인해 주세요.');return tidy(value);}
      function validate(c){
        if(!c||c.version!==1||!['place','address'].includes(c.kind)||!['rendered_selected_marker_and_tiles','rendered_selected_place_detail','rendered_selected_address_panel','apple_address_geocoding','naver_local_search','naver_hub_local_search','naver_maps_geocoding'].includes(c.method)||!tidy(c.name)||!Number.isFinite(Date.parse(c.capturedAt)))fail('네이버 장소 판독을 다시 실행해 주세요.');
        text(c.name,500,'장소 이름');for(const key of ['address','roadAddress','jibunAddress'])text(c[key],1000,'주소');
        if(c.kind==='place'){
          if(!/^\d{1,30}$/.test(c.placeID)||c.selectionKey!=='place:'+c.placeID||c.sourceURL!=='https://map.naver.com/p/entry/place/'+c.placeID)fail('네이버 장소 식별자가 일치하지 않습니다.');
        }else if(c.placeID!==''||c.selectionKey!=='address:'+tidy(c.name).replace(/\s/g,'')+':'+tidy(c.address).replace(/\s/g,'')||!/^https:\/\/map\.naver\.com\/p\/[^?#]*$/.test(c.sourceURL))fail('네이버 주소 선택 정보를 확인해 주세요.');
        if(c.coordinate!=null){
          if(!coordinate(c.coordinate)||!c.point)fail('장소 좌표를 다시 읽어 주세요.');
          if(c.method==='rendered_selected_marker_and_tiles'){
            if(!Number.isFinite(c.screenResolutionMeters)||c.screenResolutionMeters<=0||c.screenResolutionMeters>5||!Number.isSafeInteger(c.tileZoom)||c.tileZoom<0||c.tileZoom>23)fail('네이버 표식 좌표를 다시 읽어 주세요.');
          }else if(c.method==='apple_address_geocoding'){
            if(c.geocodeProvider!=='Apple'||!addressMatches(c.roadAddress||c.address,c.geocodedAddress))fail('변환한 좌표의 주소가 선택한 장소 주소와 다릅니다.');
          }else if(['naver_local_search','naver_hub_local_search','naver_maps_geocoding'].includes(c.method)){
            const e=c.apiEvidence,local=c.method!=='naver_maps_geocoding',hub=c.method==='naver_hub_local_search';
            if(!e||e.provider!==(hub?'NAVER API HUB':local?'NAVER Search':'NAVER Maps')||c.geocodeProvider!==e.provider||!addressMatches(c.roadAddress||c.address,c.geocodedAddress)||![e.roadAddress,e.jibunAddress].some(a=>addressMatches(c.roadAddress||c.address,a)))fail('네이버 API 좌표의 주소가 선택한 장소와 다릅니다.');
            const scaled=local&&/^\d{9,10}$/.test(e.x)&&/^\d{9,10}$/.test(e.y);
            if(local&&(!sameName(e.name,c.name)||(!scaled&&(!hub||!/^\d{2,3}\.\d{1,15}$/.test(e.x)||!/^\d{2}\.\d{1,15}$/.test(e.y)))))fail('네이버 지역 검색 결과를 확인해 주세요.');
            const x=Number(e.x)/(scaled?1e7:1),y=Number(e.y)/(scaled?1e7:1);
            if(!coordinate({longitude:x,latitude:y})||Math.abs(x-c.coordinate.longitude)>1e-8||Math.abs(y-c.coordinate.latitude)>1e-8)fail('네이버 API 좌표 형식을 확인해 주세요.');
          }else fail('좌표 판독 근거를 다시 확인해 주세요.');
          const p=c.point.token?.split(',');
          if(p?.length!==5||p[3]!==''||p[4]!=='SIMPLE_POI'||!Number.isFinite(+p[0])||!Number.isFinite(+p[1])||!sameName(c.point.name,c.name)||Math.abs(+p[0]/20037508.342789244*180-c.coordinate.longitude)>1e-7||Math.abs(Math.atan(Math.sinh(+p[1]/6378137))*180/Math.PI-c.coordinate.latitude)>1e-7)fail('표식과 좌표의 연결이 다릅니다.');
          let name;try{name=decodeURIComponent(p[2]);}catch(_){fail('표식 이름을 읽지 못했습니다.');}if(!sameName(name,c.name))fail('표식 이름이 다릅니다.');
        }
        return c;
      }
      function merge(input){
        const before=input.before,after=input.after,detail=input.detail;
        if(!before?.ok||!after?.ok)fail(after?.message||before?.message||'선택 장소를 읽지 못했습니다.');
        if(before.selectionKey!==after.selectionKey||before.kind!==after.kind||before.placeID!==after.placeID||(before.name&&after.name&&!sameName(before.name,after.name)))fail('읽는 동안 선택 장소가 바뀌었습니다. 다시 읽어 주세요.');
        let name=after.name,address=after.address,roadAddress=after.roadAddress,jibunAddress=after.jibunAddress;
        if(after.kind==='place'){
          if(!detail?.ok||detail.placeID!==after.placeID||(before.name&&!sameName(detail.name,before.name))||(after.name&&!sameName(detail.name,after.name)))fail('지도와 장소 상세 정보가 다릅니다. 선택한 장소를 다시 읽어 주세요.');
          name=detail.name;address=detail.address;roadAddress=detail.roadAddress;jibunAddress=detail.jibunAddress;
        }
        const now=input.now;if(!Number.isFinite(now)||now<1577836800000||now>4102444800000)fail('판독 시각을 확인해 주세요.');
        const result={version:1,kind:after.kind,selectionKey:after.selectionKey,placeID:after.placeID,name,address,roadAddress,jibunAddress,sourceURL:after.sourceURL,
          coordinate:after.coordinate,point:after.coordinate?{...after.point,name,token:after.point.token.split(',').slice(0,2).concat(encodeURIComponent(name),'','SIMPLE_POI').join(',')}:null,
          tileZoom:after.tileZoom,screenResolutionMeters:after.screenResolutionMeters,coordinateIssue:after.coordinateIssue,
          capturedAt:new Date(now).toISOString(),method:after.coordinate?'rendered_selected_marker_and_tiles':after.kind==='place'?'rendered_selected_place_detail':'rendered_selected_address_panel'};
        return validate(result);
      }
      function distance(a,b){const rad=Math.PI/180,x=(a.longitude-b.longitude)*rad*Math.cos((a.latitude+b.latitude)/2*rad),y=(a.latitude-b.latitude)*rad;return Math.hypot(x,y)*6371000;}
      function normalizedAddress(value){
        return tidy(value).replace(/^대한민국\s*/,'').split(/[,(]/)[0].replace(/서울특별시/g,'서울').replace(/부산광역시/g,'부산').replace(/대구광역시/g,'대구').replace(/인천광역시/g,'인천').replace(/광주광역시/g,'광주').replace(/대전광역시/g,'대전').replace(/울산광역시/g,'울산').replace(/세종특별자치시/g,'세종').replace(/경기도/g,'경기').replace(/강원특별자치도|강원도/g,'강원').replace(/충청북도/g,'충북').replace(/충청남도/g,'충남').replace(/전북특별자치도|전라북도/g,'전북').replace(/전라남도/g,'전남').replace(/경상북도/g,'경북').replace(/경상남도/g,'경남').replace(/제주특별자치도/g,'제주');
      }
      function addressMatches(requested,returned){
        const a=normalizedAddress(requested),b=normalizedAddress(returned),compact=x=>x.replace(/\s/g,'');
        if(!a||!b||!/[가-힣].*\d/.test(a))return false;
        const road=/([가-힣0-9·.]+(?:대로|로|길))\s*(\d+(?:-\d+)?)(?=\s|$)/,ra=road.exec(a),rb=road.exec(b);
        if(ra){
          if(!rb||ra[1]!==rb[1]||ra[2]!==rb[2])return false;
          const prefix=compact(a.slice(0,ra.index));return prefix.length>=2&&compact(b.slice(0,rb.index)).includes(prefix);
        }
        return compact(a)===compact(b); // Exact lot-number address only; never accept a district centroid.
      }
      function geocode(input){
        const c=copy(validate(input.capture)),candidates=input.candidates;
        if(!Array.isArray(candidates))fail('주소 변환 결과를 확인해 주세요.');
        const exact=candidates.filter(v=>v?.countryCode==='KR'&&coordinate(v.coordinate)&&addressMatches(c.roadAddress||c.address,v.address));
        if(!exact.length)fail('선택한 주소와 일치하는 건물 좌표를 찾지 못했습니다.');
        if(exact.some(v=>distance(v.coordinate,exact[0].coordinate)>5))fail('같은 주소에 여러 좌표가 나왔습니다. 지도에서 실제 하역 위치를 선택해 주세요.');
        const chosen=exact[0],lon=chosen.coordinate.longitude,lat=chosen.coordinate.latitude;
        c.coordinate={longitude:lon,latitude:lat};c.point={name:c.name,token:[(lon/180*20037508.342789244).toFixed(3),(6378137*Math.log(Math.tan(Math.PI/4+lat*Math.PI/360))).toFixed(3),encodeURIComponent(c.name),'','SIMPLE_POI'].join(',')};
        c.method='apple_address_geocoding';c.geocodeProvider='Apple';c.geocodedAddress=text(chosen.address,1000,'변환 결과 주소');c.tileZoom=null;c.screenResolutionMeters=null;c.coordinateIssue='';
        return validate(c);
      }
      function matchesSavedRow(input){
        const c=validate(input.capture),row=input.row;
        if(!row||!tidy(row.name))return false;
        if(tidy(row.address))return [c.address,c.roadAddress,c.jibunAddress].some(address=>addressMatches(row.address,address));
        return sameName(row.name,c.name);
      }
      function customerMatches(input){
        const a=input.first,b=input.second;
        if(!a||!b||!sameName(a.name,b.name))return false;
        return [a.roadAddress,a.address,a.jibunAddress].some(x=>[b.roadAddress,b.address,b.jibunAddress].some(y=>addressMatches(x,y)));
      }
      function apiCoordinate(input){
        const c=copy(validate(input.capture)),e=copy(input.evidence),hub=e?.provider==='NAVER API HUB',local=hub||e?.provider==='NAVER Search';
        if(!e||!['NAVER Search','NAVER API HUB','NAVER Maps'].includes(e.provider))fail('네이버 API 결과를 확인해 주세요.');
        const scaled=local&&/^\d{9,10}$/.test(e.x)&&/^\d{9,10}$/.test(e.y);
        const lon=Number(e.x)/(scaled?1e7:1),lat=Number(e.y)/(scaled?1e7:1);
        c.coordinate={longitude:lon,latitude:lat};c.point={name:c.name,token:[(lon/180*20037508.342789244).toFixed(3),(6378137*Math.log(Math.tan(Math.PI/4+lat*Math.PI/360))).toFixed(3),encodeURIComponent(c.name),'','SIMPLE_POI'].join(',')};
        c.method=hub?'naver_hub_local_search':local?'naver_local_search':'naver_maps_geocoding';c.geocodeProvider=e.provider;c.apiEvidence=e;
        c.geocodedAddress=[e.roadAddress,e.jibunAddress].find(a=>addressMatches(c.roadAddress||c.address,a))||'';
        c.coordinateIssue='';c.tileZoom=null;c.screenResolutionMeters=null;return validate(c);
      }
      function enrich(input){
        const capture=copy(validate(input.capture)),map=validate(input.map);
        if(capture.kind!=='place'||capture.selectionKey!==map.selectionKey||!sameName(capture.name,map.name)||!coordinate(map.coordinate))fail('선택한 장소와 좌표 지도의 장소가 다릅니다. 다시 읽어 주세요.');
        if(capture.address&&map.address&&!sameName(capture.address,map.address))fail('좌표를 읽는 동안 장소 주소가 바뀌었습니다. 다시 읽어 주세요.');
        for(const key of ['coordinate','point','tileZoom','screenResolutionMeters','method'])capture[key]=copy(map[key]);
        capture.coordinateIssue='';return validate(capture);
      }
      function sameSelection(input){
        const c=validate(input.capture),fresh=validate(input.fresh);
        if(c.selectionKey!==fresh.selectionKey||!sameName(c.name,fresh.name)||['address','roadAddress','jibunAddress'].some(k=>c[k]!==fresh[k]))return {same:false};
        if(input.useCoordinate&&(!coordinate(c.coordinate)||!coordinate(fresh.coordinate)||distance(c.coordinate,fresh.coordinate)>Math.max(c.screenResolutionMeters||0.05,fresh.screenResolutionMeters||0.05)*2))return {same:false};
        return {same:true};
      }
      function previousCoordinate(plan,id){
        const v=id==='depot'?null:id==='destination'?plan.destination:plan.visits.find(v=>v.id===id),explicit=id==='depot'?plan.tmapOrigin:v?.tmapCoordinate;
        if(coordinate(explicit))return explicit;
        const access=id==='depot'?plan.originAccess:v?.roadAccess;
        if(access?.curbConfirmed){const parts=access.curbPoint?.token?.split(',');if(parts?.length===5&&Math.abs(+parts[0])>1000000){const c={longitude:+parts[0]/20037508.342789244*180,latitude:Math.atan(Math.sinh(+parts[1]/6378137))*180/Math.PI};if(coordinate(c))return c;}}
        return null;
      }
      function attach(input){
        const capture=copy(validate(input.capture)),p=copy(input.plan),use=input.useCoordinate===true,id=input.targetID;
        if(!p||!Array.isArray(p.visits))fail('배송계획을 확인해 주세요.');
        const requestAddress=text(input.requestAddress,1000,'요청 상세주소');
        if(use&&(!coordinate(capture.coordinate)||input.curbConfirmed!==true))fail('선택 표식이 실제 차량 정차 위치인지 확인해 주세요.');
        if(!use&&!requestAddress)fail('가져올 주소가 없습니다. 장소 홈 화면에서 주소를 표시하고 다시 읽어 주세요.');
        let visit;
        if(id==='new'){
          if(p.visits.length>=30)fail('거래처는 최대 30곳까지 등록할 수 있습니다.');
          if(!input.newVisit)fail('새 거래처 이름과 식별자를 확인해 주세요.');
          visit=copy(input.newVisit);if(!visit||typeof visit.id!=='string'||!visit.id||['depot','destination'].includes(visit.id)||p.visits.some(v=>v.id===visit.id)||!text(visit.name,500,'거래처 이름'))fail('새 거래처 이름과 식별자를 확인해 주세요.');
          const duplicate=p.visits.find(v=>v.naverPlace?.selectionKey===capture.selectionKey);
          if(duplicate)fail('이미 연결한 장소입니다. 기존 거래처 '+duplicate.name+'에 연결해 주세요.');
          p.visits.push(visit);
        }else if(id!=='depot'){
          visit=id==='destination'?p.destination:p.visits.find(v=>v.id===id);if(!visit)fail('연결할 거래처가 변경됐습니다. 다시 선택해 주세요.');
        }
        const stopID=id==='new'?visit.id:id,old=previousCoordinate(p,stopID);
        const previousCapture=stopID==='depot'?p.naverOrigin:visit.naverPlace;
        let previousValid=false;try{validate(previousCapture);previousValid=true;}catch(_){}
        const keepActual=use&&old&&previousValid&&previousCapture.selectionKey===capture.selectionKey&&coordinate(previousCapture.coordinate)&&distance(old,previousCapture.coordinate)<0.05&&distance(old,capture.coordinate)<=Math.max(previousCapture.screenResolutionMeters||0,capture.screenResolutionMeters)*2;
        const changed=use&&!keepActual&&(old?distance(old,capture.coordinate)>0.05:(p.legs||[]).some(leg=>leg.fromID===stopID||leg.toID===stopID));
        if(keepActual){capture.coordinate={longitude:old.longitude,latitude:old.latitude};capture.point=copy(previousCapture.point);}
        capture.requestAddress=requestAddress;
        if(stopID==='depot')p.naverOrigin=capture;else visit.naverPlace=capture;
        if(use){
          const point={longitude:keepActual?old.longitude:capture.coordinate.longitude,latitude:keepActual?old.latitude:capture.coordinate.latitude,detailAddress:requestAddress,poiID:null};
          if(stopID==='depot')p.tmapOrigin=point;else visit.tmapCoordinate=point;
          const access={roadType:'',curbConfirmed:false,note:'',...copy((stopID==='depot'?p.originAccess:visit.roadAccess)||{})};
          if(!keepActual||!access.curbPoint)access.curbPoint=copy(keepActual?previousCapture.point:capture.point);
          access.curbConfirmed=true;
          if(changed){access.curbEntranceToken=null;if(access.bikeEntrance)access.bikeEntrance.entranceConfirmed=false;}
          if(stopID==='depot')p.originAccess=access;else visit.roadAccess=access;
        }else{
          const current=stopID==='depot'?p.tmapOrigin:visit.tmapCoordinate;
          if(current)current.detailAddress=requestAddress;
        }
        let invalidated=0;
        if(changed){
          for(const leg of p.legs||[])if(leg.fromID===stopID||leg.toID===stopID){leg.locationInvalidated=true;invalidated++;}
          if(p.tmapBinding){p.tmapBinding=null;for(const leg of p.legs||[])if(leg.source==='tmap')leg.locationInvalidated=true;}
        }
        if(id==='new'&&p.tmapBinding){p.tmapBinding=null;for(const leg of p.legs||[])if(leg.source==='tmap')leg.locationInvalidated=true;}
        return {plan:p,stopID,invalidated,coordinateChanged:!!changed};
      }
      function selectCustomers(input){
        let p=copy(input.plan);const customers=input.customers,selected=input.selectedIDs;
        if(!p||!Array.isArray(p.visits)||!Array.isArray(customers)||!Array.isArray(selected)||new Set(selected).size!==selected.length)fail('이번 배송 거래처 선택을 확인해 주세요.');
        const known=new Set(customers.map(c=>c.id));if(known.size!==customers.length||selected.some(id=>!known.has(id)))fail('거래처 목록이 변경됐습니다. 다시 선택해 주세요.');
        if(selected.length>30)fail('이번 배송은 최대 30곳까지 선택할 수 있습니다. 전체 거래처 목록은 그대로 보관됩니다.');
        const wanted=new Set(selected),find=v=>customers.find(c=>c.template?.id===v.id||(c.capture&&v.naverPlace?.selectionKey===c.capture.selectionKey));
        const removed=p.visits.filter(v=>{const c=find(v);return c&&!wanted.has(c.id);}).map(v=>v.id);
        p.visits=p.visits.filter(v=>!removed.includes(v.id));
        p.legs=(p.legs||[]).filter(l=>!removed.includes(l.fromID)&&!removed.includes(l.toID));
        if(p.cargo?.lots)p.cargo.lots=p.cargo.lots.filter(l=>!removed.includes(l.loadAt)&&!removed.includes(l.unloadAt));
        if(p.cargo?.autoLayout?.transfers)p.cargo.autoLayout.transfers=p.cargo.autoLayout.transfers.filter(t=>!removed.includes(t.fromID)&&!removed.includes(t.toID));
        for(const visit of p.visits){visit.afterIDs=(visit.afterIDs||[]).filter(id=>!removed.includes(id));if(removed.includes(visit.immediatelyAfterID))visit.immediatelyAfterID='';}
        let changed=removed.length>0;
        for(const customer of customers.filter(c=>wanted.has(c.id))){
          let existing=p.visits.find(v=>v.id===customer.template?.id||(customer.capture&&v.naverPlace?.selectionKey===customer.capture.selectionKey));
          if(existing&&previousCoordinate(p,existing.id))continue; // Preserve a separately confirmed vehicle position.
          const candidate=copy(customer.template);
          if(!candidate||!candidate.id||['depot','destination'].includes(candidate.id)||!text(candidate.name,500,'거래처 이름'))fail('거래처 저장 정보를 확인해 주세요.');
          if(customer.capture){
            const capture=validate(customer.capture);if(!coordinate(capture.coordinate))fail(customer.name+'의 좌표를 다시 읽어 주세요.');
            if(input.curbConfirmed!==true)fail('이번 배송에 사용할 선택 좌표가 실제 정차 위치인지 확인해 주세요.');
            p=attach({plan:p,capture,targetID:existing?existing.id:'new',newVisit:candidate,useCoordinate:true,curbConfirmed:true,requestAddress:capture.requestAddress||capture.roadAddress||capture.address}).plan;
          }else if(!existing){
            if(p.visits.some(v=>v.id===candidate.id))fail('거래처 식별자가 중복됐습니다.');
            p.visits.push(candidate);
          }
          if(!existing)changed=true;
        }
        if(p.visits.length>30)fail('이번 배송은 최대 30곳까지 선택할 수 있습니다.');
        const ids=new Set(p.visits.map(v=>v.id));for(const v of p.visits){v.afterIDs=(v.afterIDs||[]).filter(id=>ids.has(id));if(v.immediatelyAfterID&&!ids.has(v.immediatelyAfterID))v.immediatelyAfterID='';}
        if(changed){p.tmapBinding=null;for(const leg of p.legs)if(leg.source==='tmap')leg.locationInvalidated=true;}
        return p;
      }
      function endpoints(input){
        const p=copy(input.plan),customers=input.customers;
        if(!p||!Array.isArray(p.visits)||!Array.isArray(customers)||!['return','custom','last'].includes(input.endMode))fail('출발지·도착지 선택을 확인해 주세요.');
        const signature=JSON.stringify([p.originName,p.tmapOrigin,p.originAccess,p.destination,p.returnToOrigin]);
        function selected(id){
          const record=customers.find(c=>c.id===id);if(!record?.template)fail('선택한 출발지·도착지가 목록에 없습니다.');
          const v=record.template,actual=previousCoordinate({visits:[v]},v.id),capture=record.capture?copy(validate(record.capture)):null;
          if(!actual&&(!capture?.coordinate||input.curbConfirmed!==true))fail('출발지·도착지의 좌표와 실제 정차 위치를 확인해 주세요.');
          const coord=actual||capture.coordinate,requestAddress=v.tmapCoordinate?.detailAddress||capture?.requestAddress||capture?.roadAddress||capture?.address||'';
          const access=copy(v.roadAccess||{roadType:'',curbConfirmed:false,note:''});
          if(!actual){access.curbPoint=copy(capture.point);access.curbConfirmed=true;access.curbEntranceToken=null;if(access.bikeEntrance)access.bikeEntrance.entranceConfirmed=false;}
          return {name:text(record.name,500,'출발지·도착지 이름'),tmapCoordinate:{...coord,detailAddress:requestAddress,poiID:v.tmapCoordinate?.poiID||null},roadAccess:access,naverPlace:capture,customerID:id};
        }
        if(input.originID!=='current'){
          const value=selected(input.originID);p.originName=value.name;p.tmapOrigin=value.tmapCoordinate;p.originAccess=value.roadAccess;p.naverOrigin=value.naverPlace;p.originCustomerID=value.customerID;
        }
        p.returnToOrigin=input.endMode!=='last';p.destination=input.endMode==='custom'?selected(input.destinationID):null;
        if(signature!==JSON.stringify([p.originName,p.tmapOrigin,p.originAccess,p.destination,p.returnToOrigin])){
          p.tmapBinding=null;for(const leg of p.legs||[])if(leg.source==='tmap'||['depot','destination'].includes(leg.fromID)||['depot','destination'].includes(leg.toID))leg.locationInvalidated=true;
        }
        return p;
      }
      const api={merge,validate,sameSelection,attach,enrich,selectCustomers,endpoints,geocode,addressMatches,matchesSavedRow,apiCoordinate,customerMatches};
      for(const name of ['merge','sameSelection','attach','enrich','validate','selectCustomers','endpoints','geocode','matchesSavedRow','apiCoordinate','customerMatches'])api[name+'JSON']=value=>{try{const input=JSON.parse(value);return JSON.stringify({ok:true,value:api[name](name==='validate'?input.capture:input)});}catch(e){return JSON.stringify({ok:false,message:e.message});}};
      return api;
    })();
    if(typeof module!=='undefined')module.exports=DeliveryNaverPlaces;
    """#
}
