"""Generate a bundled-accessor-free Swift source containing the tested JS engine."""
from pathlib import Path
root = Path(__file__).resolve().parent.parent
source = "\n".join((root / ("scripts/" + name)).read_text().rstrip("\n") for name in ["cargo.js", "auto_cargo.js", "roads.js", "planner.js", "route_update.js", "trip.js", "drive.js"])
assert '\\#' not in source and '"""#' not in source
lines = ["// Generated by scripts/embed_planner.py", "enum PlannerEngineSource {", '    static let source = #"""']
lines += ["    " + line for line in source.split("\n")]
lines += ['    """#', "}", ""]
(root / "DeliveryRouteProbe.swiftpm/PlannerEngineSource.swift").write_text("\n".join(lines))
print("Embedded planner engine")

tmap = (root / "scripts/tmap.js").read_text().rstrip("\n")
assert '\\#' not in tmap and '\"\"\"#' not in tmap
(root / "DeliveryRouteProbe.swiftpm/TMapEngineSource.swift").write_text("// Generated by scripts/embed_planner.py\nenum TMapEngineSource {\n    static let source = #\"\"\"\n" + "\n".join("    " + line for line in tmap.split("\n")) + "\n    \"\"\"#\n}\n")

road = (root / "scripts/roads.js").read_text().rstrip("\n")
assert '\\#' not in road and '"""#' not in road
(root / "DeliveryRouteProbe.swiftpm/RoadEngineSource.swift").write_text("// Generated by scripts/embed_planner.py\nenum RoadEngineSource {\n    static let source = #\"\"\"\n" + "\n".join("    " + line for line in road.split("\n")) + "\n    \"\"\"#\n}\n")
