"""Embed the existing reader as a Swift raw string, without bundle resources.

Run after editing scripts/capture.js. This script is a development helper;
Swift Playgrounds needs only the files inside DeliveryRouteProbe.swiftpm.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
source = (ROOT / "scripts" / "capture.js").read_text(encoding="utf-8").rstrip("\n")
target = ROOT / "DeliveryRouteProbe.swiftpm" / "BrowserModel.swift"
start_marker = "// BEGIN EMBEDDED ROUTE CAPTURE SCRIPT"
end_marker = "// END EMBEDDED ROUTE CAPTURE SCRIPT"

if '"""#' in source or "\\#" in source:
    raise ValueError("Reader contains a raw-string delimiter or escape. Use a longer delimiter before embedding.")

block = "\n".join([
    start_marker,
    "// Generated by scripts/embed_capture_script.py. Keep JavaScript escapes literal.",
    "private enum RouteCaptureScript {",
    '    static let source = #"""',
    *["    " + line for line in source.split("\n")],
    '    """#',
    "}",
    end_marker,
])

text = target.read_text(encoding="utf-8")
if start_marker in text:
    start = text.index(start_marker)
    end = text.index(end_marker, start) + len(end_marker)
    text = text[:start] + block + text[end:]
else:
    text = text.rstrip() + "\n\n" + block + "\n"
target.write_text(text, encoding="utf-8")
print("Embedded route reader in BrowserModel.swift")

blocks=[]
for name,file in [("VehicleProfileScript","vehicle_profile.js"),("PeekVehicleScript","peek_vehicle_profile.js"),("BikeEndpointScript","bike_endpoint.js"),("PrepareBikeEndpointScript","prepare_bike_endpoint.js"),("NaverPlaceRootScript","naver_place_root.js"),("NaverPlaceDetailScript","naver_place_detail.js"),("NaverFrameBridgeScript","naver_frame_bridge.js"),("NaverFrameRequestScript","naver_frame_request.js"),("NaverSavedListScript","naver_saved_list.js"),("NaverMapPanelScript","naver_map_panel.js")]:
    js=(ROOT / "scripts" / file).read_text().rstrip("\n")
    assert '\\#' not in js and '"""#' not in js
    blocks.append("enum " + name + " {\n    static let source = #\"\"\"\n" + "\n".join("    " + line for line in js.split("\n")) + "\n    \"\"\"#\n}")
(ROOT / "DeliveryRouteProbe.swiftpm/MapSupportSource.swift").write_text("// Generated by scripts/embed_capture_script.py\n"+"\n".join(blocks)+"\n")

js=(ROOT / "scripts/naver_places.js").read_text().rstrip("\n")
assert '\\#' not in js and '"""#' not in js
(ROOT / "DeliveryRouteProbe.swiftpm/NaverPlaceEngineSource.swift").write_text("// Generated by scripts/embed_capture_script.py\nenum NaverPlaceEngineSource {\n    static let source = #\"\"\"\n"+"\n".join("    "+line for line in js.split("\n"))+"\n    \"\"\"#\n}\n")

js=(ROOT / "scripts/naver_api.js").read_text().rstrip("\n")
assert '\\#' not in js and '\"\"\"#' not in js
(ROOT / "DeliveryRouteProbe.swiftpm/NaverAPIEngineSource.swift").write_text("// Generated by scripts/embed_capture_script.py\nenum NaverAPIEngineSource {\n    static let source = #\"\"\"\n"+"\n".join("    "+line for line in js.split("\n"))+"\n    \"\"\"#\n}\n")
